package final_project_2026;
import java.util.Random;  
import becker.robots.*;
import java.awt.Color;

/**
 * this is the core engine for the zombie outbreak game
 * handles spawning map generation interaction logic and the main game loop
 * @author ayyan
 * @author adam
 * @author spencer
 * @version june 2 2026
 */
public class OutbreakApp {

	private static boolean isGameOver = false;
	private static int targetThingsToWin = 25; 
	private static int currentThingsCollected = 0;
	private static int totalTurns = 0; 

	private static int playerCount = 12;
	private static int startingZombieCount = 5;
	private static int maxThings;
	private static int currentThingsOnBoard = 0;
	private static final int MEDIC_SPEED = 12;

	private static final Random rand = new Random();
	
	private static GameRobot[] players = new GameRobot[playerCount];
	private static RobotInfoRecord[] records = new RobotInfoRecord[playerCount];
	private static City playground = new City(15, 26);

	/**
	 * entry point for simulation
	 * @param args command line arguments
	 */
	public static void main(String[] args) { 
		setupCity();
		spawnPlayers();

		int survivorCount = playerCount - startingZombieCount - 1; 
		maxThings = survivorCount * 3;
		manageThings();

		System.out.println("--- outbreak game started ---");

		while (!isGameOver) { 
			updateRecords();
			manageThings();
			runGameLoop();
			totalTurns++; 
			checkWinConditions();
		}
	}

	/**
	 * constructs perimeter walls for simulation area
	 */
	private static void setupCity() {
		for (int a = 0; a <= 25; a++) {
			new Wall(playground, 0, a, Direction.NORTH);
			new Wall(playground, 14, a, Direction.SOUTH);
		}

		for (int s = 0; s <= 14; s++) {
			new Wall(playground, s, 0, Direction.WEST);
			new Wall(playground, s, 25, Direction.EAST);
		}
	}

	/**
	 * randomizes locations speeds abilities and instantiates all starting players
	 */
	private static void spawnPlayers() {
		int mStreet = generateRandomNumber(1, 13);
		int mAve = generateRandomNumber(1, 24);
		players[0] = new MedicRobot(playground, mStreet, mAve, Direction.NORTH, 0, MEDIC_SPEED, true, playerCount);
		players[0].setColor(Color.WHITE);

		for (int i = 1; i <= startingZombieCount; i++) {
			int zStreet = generateRandomNumber(1, 13);
			int zAve = generateRandomNumber(1, 24);
			int zSpeed = generateRandomNumber(1, 5); 
			int zAttack = generateRandomNumber(1, 100);

			players[i] = new ZombieRobot(playground, zStreet, zAve, Direction.NORTH, i, zSpeed, zAttack, playerCount);
			players[i].setColor(Color.GREEN);
		}

		for (int i = startingZombieCount + 1; i < playerCount; i++) {
			int sStreet = generateRandomNumber(1, 13);
			int sAve = generateRandomNumber(1, 24);
			int sSpeed = generateRandomNumber(1, 5); 
			int sEvade = generateRandomNumber(1, 100);

			players[i] = new SurvivorRobot(playground, sStreet, sAve, Direction.NORTH, i, sSpeed, sEvade);
			players[i].setColor(Color.ORANGE);
		}
	}

	/**
	 * maintains item count on game board
	 */
	private static void manageThings() {
		if (currentThingsOnBoard < (maxThings / 2)) {
			int thingsToSpawn = maxThings - currentThingsOnBoard;

			for (int i = 0; i < thingsToSpawn; i++) {
				int tStreet = generateRandomNumber(1, 13);
				int tAve = generateRandomNumber(1, 24);
				new Thing(playground, tStreet, tAve);
				currentThingsOnBoard++;
			}
		}
	}

	/**
	 * populates record array with current player states
	 */
	private static void updateRecords() {
		for (int i = 0; i < playerCount; i++) {
			if (players[i] != null) {
				records[i] = generateRecord(players[i]);
			}
			else {
				records[i] = null;
			}
		}
	}

	/**
	 * executes turn logic for all active players
	 */
	private static void runGameLoop() {
		for (int i = 0; i < playerCount; i++) { 
			if (players[i] == null) {
				continue;
			}
			TurnAction response = players[i].takeTurn(records);
			
			int distanceRequested = Math.abs(response.getTargetStreet() - players[i].getStreet()) 
					+ Math.abs(response.getTargetAvenue() - players[i].getAvenue());

			if (distanceRequested <= players[i].getSpeed()) {
				executeAction(players[i], response);
			}

			records[i] = generateRecord(players[i]);
		}
	}

	/**
	 * executes physical movement and resolves combat interaction dice rolls
	 * @param bot the robot performing the action
	 * @param action the instructions generated by the robot ai
	 */
	private static void executeAction(GameRobot bot, TurnAction action) {
		moveRobot(bot, action.getTargetStreet(), action.getTargetAvenue());
		String intent = action.getIntent();

		if (intent.equals(TurnAction.PICK_UP)) {
			if (bot.canPickThing()) {
				bot.pickThing();
				currentThingsOnBoard--;
				currentThingsCollected++;
				System.out.println("robot " + bot.getId() + " gathered a thing");
			}
		}

		if (intent.equals(TurnAction.INFECT)) {
			resolveCombat(bot, action.getTargetBot());
		}

		if (bot.getAvenue() == players[action.getTargetBot()].getAvenue() && bot.getStreet() == players[action.getTargetBot()].getStreet() && intent.equals(TurnAction.HEAL)) {
			System.out.println("medic attempting to heal robot " + action.getTargetBot());
			resolveCombat(bot, action.getTargetBot());
		}
	}

	/**
	 * calculates quadrants rolls dice and determines if infection succeeds
	 * @param attacker the robot attempting the interaction
	 * @param targetId the id of the robot defending
	 */
	private static void resolveCombat(GameRobot attacker, int targetId) {
		GameRobot defender = players[targetId];

		int attackerAbility = attacker.getCombatAbility();
		int defenderAbility = defender.getCombatAbility();

		int attackerDice = getQuadrant(attackerAbility);
		int defenderDice = getQuadrant(defenderAbility);

		int attackerRoll = rollHighest(attackerDice);
		int defenderRoll = rollHighest(defenderDice);

		if (attacker.getRole().equals("MEDIC")) {
			if (attackerRoll > defenderRoll) {
				System.out.println("medic successfully healed zombie " + attackerRoll + " vs " + defenderRoll);
				swapRobotClass(targetId, false);
			}
			else {
				System.out.println("zombie resisted healing " + defenderRoll + " vs " + attackerRoll);
			}
		}

		if (attacker.getRole().equals("ZOMBIE")) {
			if (attackerRoll > defenderRoll) {
				System.out.println("zombie successfully infected survivor " + attackerRoll + " vs " + defenderRoll);
				swapRobotClass(targetId, true);
			} else {
				System.out.println("survivor successfully dodged infection " + defenderRoll + " vs " + attackerRoll);
				
				if (defender.getRole().equals("SURVIVOR")) {
					defender.registerSuccessfulDodge();
				}
			}
		}
	}

	/**
	 * figures out which quadrant the ability falls in to determine dice count
	 * @param ability the stat from 1 to 100
	 * @return int number of dice to roll
	 */
	private static int getQuadrant(int ability) {
		if (ability <= 25) { 
			return 1; 
		}
		if (ability <= 50) { 
			return 2; 
		}
		if (ability <= 75) { 
			return 3; 
		}
		return 4;
	}

	/**
	 * rolls standard d6 dice and returns the highest result
	 * @param numDice the amount of dice to roll
	 * @return int the highest dice roll
	 */
	private static int rollHighest(int numDice) {
		int highest = 0;
		for (int i = 0; i < numDice; i++) {
			int roll = generateRandomNumber(1, 6);
			if (roll > highest) {
				highest = roll;
			}
		}
		return highest;
	}

	/**
	 * Replaces a robot object with a new instance of a different class, 
	 * transferring coordinates and applying class-specific logic (like item loss).
	 * @param targetId the id of the robot being swapped
	 * @param toZombie true if converting survivor to zombie, false if zombie to survivor
	 */
	private static void swapRobotClass(int targetId, boolean toZombie) {
		if (toZombie && players[targetId].getRole().equals("SURVIVOR")) {
			int itemsLost = players[targetId].countThingsInBackpack();
			currentThingsCollected -= itemsLost;
			if (itemsLost > 0) {
				System.out.println("survivor " + targetId + " was infected and lost " + itemsLost + " items!");
			}
		}

		players[targetId].setTransparency(1.0);

		int st = players[targetId].getStreet();
		int ave = players[targetId].getAvenue();
		Direction dir = players[targetId].getDirection();
		int speed = generateRandomNumber(1, 4);

		if (toZombie) {
			int attack = generateRandomNumber(1, 100);
			players[targetId] = new ZombieRobot(playground, st, ave, dir, targetId, speed, attack, playerCount);
			players[targetId].setColor(Color.GREEN);
		} 
		else {
			int evade = generateRandomNumber(1, 100);
			players[targetId] = new SurvivorRobot(playground, st, ave, dir, targetId, speed, evade);
			players[targetId].setColor(Color.ORANGE);
		}
	}

	/**
	 * translates target coordinates into physical robot movements
	 * @param bot robot entity
	 * @param targetStreet target street
	 * @param targetAvenue target avenue
	 */
	private static void moveRobot(GameRobot bot, int targetStreet, int targetAvenue) {
		if (bot.getStreet() > targetStreet) {
			while (bot.getDirection() != Direction.NORTH) { 
				bot.turnLeft(); 
			}
			while (bot.getStreet() != targetStreet) { 
				bot.move(); 
			}
		} 
		else if (bot.getStreet() < targetStreet) {
			while (bot.getDirection() != Direction.SOUTH) { 
				bot.turnLeft(); 
			}
			while (bot.getStreet() != targetStreet) { 
				bot.move(); 
			}
		}

		if (bot.getAvenue() > targetAvenue) {
			while (bot.getDirection() != Direction.WEST) { 
				bot.turnLeft(); 
			}
			while (bot.getAvenue() != targetAvenue) { 
				bot.move(); 
			}
		} 
		else if (bot.getAvenue() < targetAvenue) {
			while (bot.getDirection() != Direction.EAST) { 
				bot.turnLeft(); 
			}
			while (bot.getAvenue() != targetAvenue) { 
				bot.move(); 
			}
		}
	}

	/**
	 * evaluates state to determine if game should end
	 */
	private static void checkWinConditions() {
		if (currentThingsCollected >= targetThingsToWin) {
			System.out.println("survivors win in " + totalTurns + " turns they collected " + currentThingsCollected + " things");
			isGameOver = true;
			return;
		}

		int survivorsLeft = 0;
		for (int i = 0; i < playerCount; i++) {
			if (players[i] != null && !players[i].isZombie() && players[i].getId() != 0) {
				survivorsLeft++;
			}
		}

		if (survivorsLeft == 0) {
			System.out.println("zombies win in " + totalTurns + " turns all survivors are infected");
			isGameOver = true;
		}
	}

	/**
	 * generates records to update the game state when needed
	 * @param bot the robot to be updated
	 * @return robot info record with new updates, for survivor dynamic speed which changes with amount of items carried
	 * @author spencer
	 */
	private static RobotInfoRecord generateRecord(GameRobot bot) {
		if (!bot.isZombie()) {
			int dynamicSurvivorSpeed = (int) Math.max(1, bot.getSpeed() - bot.countThingsInBackpack()); 
			return new RobotInfoRecord(bot.getId(), bot.getStreet(), bot.getAvenue(), dynamicSurvivorSpeed, bot.isZombie(), bot.countThingsInBackpack());
		}
		else {
			return new RobotInfoRecord(bot.getId(), bot.getStreet(), bot.getAvenue(), (int) bot.getSpeed(), bot.isZombie(), 0);
		}
	}

	/**
	 * Generates a random integer between a specified minimum and maximum value.
	 * @param min the lowest possible number
	 * @param max the highest possible number
	 * @return int the generated random number
	 */
	private static int generateRandomNumber(int min, int max) {
		return rand.nextInt(max - min + 1) + min;
	}
}
