package final_project_2026;
import java.util.ArrayList;
import java.util.Random;  
import becker.robots.*;

import java.awt.Color;

/**
 * this is the core engine for the zombie outbreak game
 * handles spawning map generation interaction logic and the main game loop
 * @author ayyan
 * @author adam
 * @author spencer
 * @version june 2 2026
 */
public class OutbreakApp {

	// static variables so the main loop can read them
	private static boolean isGameOver = false;
	private static int targetThingsToWin = 15;
	private static int currentThingsCollected = 0;

	// customizable game parameters
	private static int playerCount = 12;
	private static int startingZombieCount = 5;
	private static int maxThings;
	private static int currentThingsOnBoard = 0;
	private static final int MEDIC_SPEED = 4;

	private static final Random rand = new Random();
	public static ArrayList<ZombieInfoRecord> zombieRecords; 

	
	private static GameRobot[] players = new GameRobot[playerCount];
	private static RobotInfoRecord[] records = new RobotInfoRecord[playerCount];
	private static City playground = new City(15, 26);

	public static void main(String[] args) { 
		setupCity();
		spawnPlayers();

		int survivorCount = playerCount - startingZombieCount - 1; 
		maxThings = survivorCount * 3;
		manageThings();

		System.out.println("--- outbreak game started ---");

		while (!isGameOver) { 
			updateRecords();
			manageThings();
			runGameLoop();
			checkWinConditions();
		}
	}

	private static void setupCity() {
		// loop to build horizontal walls
		for (int a = 0; a <= 25; a++) {
			new Wall(playground, 0, a, Direction.NORTH);
			new Wall(playground, 14, a, Direction.SOUTH);
		}

		// loop to build vertical walls
		for (int s = 0; s <= 14; s++) {
			new Wall(playground, s, 0, Direction.WEST);
			new Wall(playground, s, 25, Direction.EAST);
		}
	}

	/**
	 * randomizes locations speeds abilities and instantiates all starting players
	 */
	private static void spawnPlayers() {
		// spawn medic first at id 0
		int mStreet = generateRandomNumber(1, 13);
		int mAve = generateRandomNumber(1, 24);
		players[0] = new MedicRobot(playground, mStreet, mAve, Direction.NORTH, 0, MEDIC_SPEED, true);
		players[0].setColor(Color.WHITE);

		// loop to spawn zombies
		for (int i = 1; i <= startingZombieCount; i++) {
			int zStreet = generateRandomNumber(1, 13);
			int zAve = generateRandomNumber(1, 24);
			int zSpeed = generateRandomNumber(1, 4);
			int zAttack = generateRandomNumber(1, 100);

			players[i] = new ZombieRobot(playground, zStreet, zAve, Direction.NORTH, i, zSpeed, zAttack, playerCount);
			players[i].setColor(Color.GREEN);
		}

		// loop to spawn survivors
		for (int i = startingZombieCount + 1; i < playerCount; i++) {
			int sStreet = generateRandomNumber(1, 13);
			int sAve = generateRandomNumber(1, 24);
			int sSpeed = generateRandomNumber(5, 8);
			int sEvade = generateRandomNumber(1, 100);

			players[i] = new SurvivorRobot(playground, sStreet, sAve, Direction.NORTH, i, sSpeed, sEvade);
			players[i].setColor(Color.ORANGE);
		}
	}

	private static void manageThings() {
		// check if things dropped below half
		if (currentThingsOnBoard < (maxThings / 2)) {
			int thingsToSpawn = maxThings - currentThingsOnBoard;

			for (int i = 0; i < thingsToSpawn; i++) {
				int tStreet = generateRandomNumber(1, 13);
				int tAve = generateRandomNumber(1, 24);
				new Thing(playground, tStreet, tAve);
				currentThingsOnBoard++;
			}
		}
	}

	private static void updateRecords() {
		// loop to populate records
		for (int i = 0; i < playerCount; i++) {
			if (players[i] != null) {
				records[i] = generateRecord(players[i]);
			}
			else {
				records[i] = null;
			}
		}
	}

	private static void runGameLoop() {
		// loop through each player
		for (int i = 0; i < playerCount; i++) { 
			if (players[i] == null) {
				continue;
			}
			TurnAction response;
			if (players[i].getRole() == "MEDIC") {
				zombieRecords = new ArrayList<ZombieInfoRecord>();
				response = players[i].takeTurn(records, zombieRecords);
			}
			else { 
				response = players[i].takeTurn(records);
			}
			int distanceRequested = Math.abs(response.getTargetStreet() - players[i].getStreet()) 
					+ Math.abs(response.getTargetAvenue() - players[i].getAvenue());

			// check if robot has enough speed to move
			if (distanceRequested <= players[i].getSpeed()) {
				executeAction(players[i], response);
			}

			records[i] = generateRecord(players[i]);
		}
	}

	/**
	 * executes physical movement and resolves combat interaction dice rolls
	 * @param bot the robot performing the action
	 * @param action the instructions generated by the robot ai
	 */
	private static void executeAction(GameRobot bot, TurnAction action) {
		moveRobot(bot, action.getTargetStreet(), action.getTargetAvenue());
		String intent = action.getIntent();

		// check if intent is to pick up thing
		if (intent.equals(TurnAction.PICK_UP)) {
			if (bot.canPickThing()) {
				bot.pickThing();
				currentThingsOnBoard--;
				currentThingsCollected++;
				System.out.println("robot " + bot.getId() + " gathered a thing");
			}
		}

		// check if intent is to infect
		if (intent.equals(TurnAction.INFECT)) {
			resolveCombat(bot, action.getTargetBot());
		}

		// check if intent is to heal
		if (bot.getAvenue() == players[action.getTargetBot()].getAvenue() && bot.getStreet() == players[action.getTargetBot()].getStreet() && intent.equals(TurnAction.HEAL)) {
			System.out.println("medic healed robot " + action.getTargetBot());
			resolveCombat(bot, action.getTargetBot());
		}
	}

	/**
	 * calculates quadrants rolls dice and determines if infection succeeds
	 * @param attacker the robot attempting the infection
	 * @param targetId the id of the robot defending
	 */
	private static void resolveCombat(GameRobot attacker, int targetId) {
		GameRobot defender = players[targetId];

		// polymorphic calls completely remove the need for instanceof checks
		int zAttackAbility = attacker.getCombatAbility();
		int sEvadeAbility = defender.getCombatAbility();

		// determine number of dice based on quadrant
		int zDice = getQuadrant(zAttackAbility);
		int sDice = getQuadrant(sEvadeAbility);

		// roll for highest numbers
		int zRoll = rollHighest(zDice);
		int sRoll = rollHighest(sDice);

		// check if zombie beat defender tie goes to defender
		if (attacker.getRole().equals("MEDIC")) {
			if (zRoll > sRoll) {
				System.out.println("Medic won interaction " + zRoll + " vs " + sRoll);
				swapRobotClass(targetId, false);
			}
			else {
				System.out.println("Zombie evaded infection " + sRoll + " vs " + zRoll);
			}
		}


		if (attacker.getRole().equals("ZOMBIE")) {
			if (zRoll > sRoll) {
				System.out.println("zombie won interaction " + zRoll + " vs " + sRoll);
				swapRobotClass(targetId, true);
			} else {
				System.out.println("survivor evaded infection " + sRoll + " vs " + zRoll);
				
				// if the defender is a survivor, tell it that it successfully dodged the attack
				if (defender instanceof SurvivorRobot) {
					((SurvivorRobot)defender).registerSuccessfulDodge();
				}
			}
		}
	}

	/**
	 * figures out which quadrant the ability falls in to determine dice count
	 * @param ability the stat from 1 to 100
	 * @return int number of dice to roll
	 */
	private static int getQuadrant(int ability) {
		if (ability <= 25) { 
			return 1; 
		}
		if (ability <= 50) { 
			return 2; 
		}
		if (ability <= 75) { 
			return 3; 
		}
		return 4;
	}

	/**
	 * rolls standard d6 dice and returns the highest result
	 * @param numDice the amount of dice to roll
	 * @return int the highest dice roll
	 */
	private static int rollHighest(int numDice) {
		int highest = 0;
		// loop for amount of dice
		for (int i = 0; i < numDice; i++) {
			int roll = generateRandomNumber(1, 6);
			if (roll > highest) {
				highest = roll;
			}
		}
		return highest;
	}

	private static void swapRobotClass(int targetId, boolean toZombie) {
		players[targetId].setTransparency(1.0);

		int st = players[targetId].getStreet();
		int ave = players[targetId].getAvenue();
		Direction dir = players[targetId].getDirection();
		int speed = generateRandomNumber(1, 4);

		if (toZombie) {
			int attack = generateRandomNumber(1, 100);
			players[targetId] = new ZombieRobot(playground, st, ave, dir, targetId, speed, attack, playerCount);
			players[targetId].setColor(Color.GREEN);
		} 
		else {
			int evade = generateRandomNumber(1, 100);
			players[targetId] = new SurvivorRobot(playground, st, ave, dir, targetId, speed, evade);
			players[targetId].setColor(Color.ORANGE);
		}
	}

	private static void moveRobot(GameRobot bot, int targetStreet, int targetAvenue) {
		if (bot.getStreet() > targetStreet) {
			while (bot.getDirection() != Direction.NORTH) { 
				bot.turnLeft(); 
			}
			while (bot.getStreet() != targetStreet) { 
				bot.move(); 
			}
		} 
		
		else if (bot.getStreet() < targetStreet) {
			while (bot.getDirection() != Direction.SOUTH) { 
				bot.turnLeft(); 
			}
			
			while (bot.getStreet() != targetStreet) { 
				bot.move(); 
			}
		}

		if (bot.getAvenue() > targetAvenue) {
			while (bot.getDirection() != Direction.WEST) { 
				
				bot.turnLeft(); 
			}
			
			while (bot.getAvenue() != targetAvenue) { 
				bot.move(); 
			}
		} 
		else if (bot.getAvenue() < targetAvenue) {
			while (bot.getDirection() != Direction.EAST) { 
				bot.turnLeft(); 
			}
			
			while (bot.getAvenue() != targetAvenue) { 
				bot.move(); 
			}
		}
	}

	private static void checkWinConditions() {
		if (currentThingsCollected >= targetThingsToWin) {
			System.out.println("survivors win they collected " + currentThingsCollected + " things");
			isGameOver = true;
			return;
		}

		int survivorsLeft = 0;
		for (int i = 0; i < playerCount; i++) {
			if (players[i] != null && !players[i].isZombie() && players[i].getId() != 0) {
				survivorsLeft++;
			}
		}

		if (survivorsLeft == 0) {
			System.out.println("zombies win all survivors are infected");
			isGameOver = true;
		}
	}

	/**
	 * generates records to update the game state when needed
	 * @param GameRobot to be updated
	 * @return robot info record with new updates, for survivor dynamic speed which changes with amount of items carried
	 * @author Spencer
	 */
	private static RobotInfoRecord generateRecord(GameRobot bot) {
		if(!bot.isZombie) {
			int dynamicSurvivorSpeed = (int) Math.max(1, bot.getSpeed() - bot.countThingsInBackpack());
			return new RobotInfoRecord(bot.getId(), bot.getStreet(), bot.getAvenue(), dynamicSurvivorSpeed, bot.isZombie(), 0);
		}
		else {
			return new RobotInfoRecord(bot.getId(), bot.getStreet(), bot.getAvenue(), (int) bot.getSpeed(), bot.isZombie(), 0);
		}

	}
	


	// Update your method:
	private static int generateRandomNumber(int min, int max) {
		return rand.nextInt(max - min + 1) + min;
	}
}
