package final_project_2026;

**
 * the main record that is generated by the main app to broadcast the game state to all robots
 * @author Adam
 * @author Ayyan
 * @author Spencer
 * @version June 12, 2026
 */
public class RobotInfoRecord {
    // instance variables to store robot data
    private int id;
    private int street; 
    private int avenue;
    private int speed;
    private int safeSpotAve;
    private int safeSpotStreet;
    private int itemsCarried;
    private boolean isZombie;
    private int dodges;
    
    // constructor to set data and intialize record
    public RobotInfoRecord(int id, int street, int avenue, int speed, boolean isZombie, int itemsCarried, int dodges) {
        this.id = id;
        this.street = street;
        this.avenue = avenue;
        this.speed = speed;
        this.isZombie = isZombie;
        this.itemsCarried = itemsCarried;
        this.dodges = dodges;
    }
    
    public RobotInfoRecord(int id, int street, int avenue, double speed, boolean isZombie, int dodges) {
        this.id        = id;
        this.street    = street;
        this.avenue    = avenue;
        this.speed     = (int) speed;
        this.isZombie  = isZombie;
        this.itemsCarried = 0;
        this.dodges = dodges;
    }
    
	public int getId() {
        return this.id;
    }
    
    public int getStreet() {
        return this.street;
    }
    
    public int getAvenue() {
        return this.avenue;
    }
    
    public int getSpeed() {
        return this.speed;
    }
    
    public boolean getIsZombie() {
        return this.isZombie;
    }
    
    public int getItemsCarried() {
        return this.itemsCarried;
    }
    
    public int getDodges() {
    		return this.dodges;
    }
}
